//HintName: Zomp.SyncMethodGenerator.IntegrationTests.EntityFrameworkQueryabl_b3d48c88.QueryableToListAsync.g.cs
// <auto-generated/>
#nullable enable

using System.Threading;
using System.Threading.Tasks;

namespace Zomp.SyncMethodGenerator.IntegrationTests
{
    using Microsoft.EntityFrameworkCore;

    public partial class EntityFrameworkQueryableExtensions
    {
        public int QueryableToList(global::Microsoft.EntityFrameworkCore.DbContext dbContext)
        {
            var dbSet = dbContext.Set<object>();
            var result = global::System.Linq.Enumerable.ToList(dbSet);
            return result.Count;
        }
    }
}
