//HintName: Zomp.SyncMethodGenerator.IntegrationTests.Caller.CallAsync.g.cs
// <auto-generated/>
#nullable enable

using System.Linq;
using System.Threading;
using System.Threading.Tasks;

namespace Zomp.SyncMethodGenerator.IntegrationTests
{
    using Custom;

    partial class Caller
    {
        public int Call(global::System.Linq.IQueryable<object> source)
        {
            return global::Custom.DocumentQueryableExtensions.Count(source);
        }
    }
}
